services:
    _defaults:
        autowire: true
        autoconfigure: true

    Clickpress\ContaoAssociationFormBundle\Controller\FrontendModule\ModuleAssociationFormController:
        public: true
        tags:
            -
                name: contao.frontend_module
                category: user
                type: association_form
