services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: true

    Clickpress\ContaoAssociationFormBundle\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection,ContaoAssociationBundle.php}

    Clickpress\ContaoAssociationFormBundle\Controller\FrontendModule\ModuleAssociationFormController:
        public: true
        tags:
            -   name: contao.frontend_module
                category: user
                type: association_form

    Clickpress\ContaoAssociationFormBundle\EventListener\ActivateAccountListener:
        arguments:
            $logger: '@?logger'
